version: '3'

services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${CONFIG}/deluge:/config
      - ${DOWNLOADS}:/downloads
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${PUID}:${PGID}
    network_mode: "host"
    volumes:
      - ${CONFIG}/jellyfin:/config
      - ${CONFIG}/jellyfin/cache:/cache      
      - ${MOVIES}:/movies
      - ${TV}:/tv
    restart: "unless-stopped"

  
  