version: '3.1'

services:
  vpn:
    container_name: vpn
    image: bubuntux/nordvpn
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun    
    environment:
      - USER=
      - PASS=
      - CONNECT=France
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
      - TZ=${TZ}
    ports:
      - 8080:80
      - 8112:8112
    restart: unless-stopped

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env 
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022
      - DELUGE_LOGLEVEL=info
    volumes:
      - ${DOWNLOADS}:/downloads # downloads folder
      - ${CONFIG}/deluge:/config # config files 

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${DOWNLOADS}/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${CONFIG}/jackett:/config # config files

#  sonarr:
#    container_name: sonarr
#    image: linuxserver/sonarr:latest
#    restart: unless-stopped
#    network_mode: host
#    environment:
#      - PUID=${PUID} # default user id, defined in .env
#      - PGID=${PGID} # default group id, defined in .env
#      - TZ=${TZ} # timezone, defined in .env
#      - UMASK_SET=022 #optional
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ${CONFIG}/sonarr:/config # config files
#      - ${TV}:/tv # tv shows folder
#      - ${DOWNLOADS}:/downloads # download folder
#    ports:
#      - 8989

#  radarr:
#    image: linuxserver/radarr
#    container_name: radarr
#    network_mode: host
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#      - UMASK_SET=022 #optional
#    volumes:
#      - ${CONFIG}/radarr:/config
#      - ${MOVIES}:/movies
#      - ${DOWNLOADS}:/downloads
#    ports:
#      - 7878

#  bazarr:
#    image: linuxserver/bazarr
#    container_name: bazarr
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#      - UMASK_SET=022 #optional
#    volumes:
#      - ${CONFIG}/bazarr:/config
#      - ${MOVIES}:/movies
#      - ${TV}:/tv
#    ports:
#      - 6767
#    restart: unless-stopped

  plex:
    container_name: plex
    image: linuxserver/plex
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - PUID=${PUID}
      - PGID=${PGID}
      - VERIONS=docker
      - UMASK_SET=022
    network_mode: host
    volumes:
      - ${CONFIG}/plex/db:/config # plex database
      - ${CONFIG}/plex/transcode:/transcode # temp transcoded files
      - ${TV}:/tv
      - ${MOVIES}:/movies
    
  rpi-monitor:
    container_name: rpi-monitor
    image: michaelmiklis/rpi-monitor
    restart: unless-stopped
    ports:
      - 8888
    devices:
      - /dev/vcsm
      - /dev/vchiq
    volumes:
      - ${CONFIG}/rpi-monitor:/etc/rpimonitor/
      - /opt/vc:/opt/vc/
      - /boot/:/boot/
      - /sys/:/dockerhost/sys/:ro
      - /etc/:/dockerhost/etc/:ro
      - /proc/:/dockerhost/proc/:ro
      - /usr/lib/:/dockerhost/usr/lib/:ro

#  muximux:
#    image: linuxserver/muximux
#    container_name: muximux
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - ${CONFIG}/muximux:/config
#    ports:
#      - 81:80
#    restart: unless-stopped


#  nextcloud:
#    image: linuxserver/nextcloud
#    container_name: nextcloud
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    volumes:
#      - ${CONFIG}/nextcloud:/config
#      - ${SHARE}/sdd:/data
#    ports:
#      - 8081:80
#    restart: unless-stopped


#  pihole:
#    container_name: pihole
#    image: pihole/pihole:latest
#    ports:
#      - 53/tcp
#      - 53/udp
#      - 67/udp
#      - 2280:80/tcp
#      - 2443:443/tcp
#    environment:
#      TZ: ${TZ}
#      WEBPASSWORD: 
    # Volumes store your data between container upgrades
 #   volumes:
#       - ${CONFIG}/etc-pihole/:/etc/pihole/
#       - ${CONFIG}/etc-dnsmasq.d/:/etc/dnsmasq.d/
#    dns:
#      - 127.0.0.1
#      - 1.1.1.1
#    # Recommended but not required (DHCP needs NET_ADMIN)
#    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#    cap_add:
#      - NET_ADMIN
#    restart: unless-stopped
